Fix some bugs and improve compatibility
sbmueller/LaTeXFiguresCleaner pull request #1
Opened 2018-05-09 05:30 UTC by DABH

Thanks for making this useful script!

- I made quotation marks consistent for style's sake
- There was also a bug, the script checked for `filename` not `os.path.join(directory, filename))`
- `os.path.join` is preferable over `+ '/'` for cross-platform compatibility
- LaTeX log files generated by Overleaf are in a strange encoding; thus I added an encoding parameter -- probably you don't usually need to use this, but it addresses the popular edge case of Overleaf at least

2018-05-10 12:31 UTC, sbmueller commented
@DABH thank you for the PR!
I agree with you on the changes. Going into review now.

2018-05-10 12:33 UTC, sbmueller requested changes

2018-05-10 12:33 UTC, sbmueller commented on clean.py
> +enc = 'Latin-1'
The encoding option is a sensible improvement, however I would prefer to let the default be UTF8 since I think it's still more common.

2018-05-11 06:12 UTC, DABH commented
Updated (with comment) -- thanks!

2018-05-11 17:36 UTC, sbmueller approved these changes

2018-05-11 17:37 UTC, merged